[package]
name = "pajbot2-points"
version = "0.1.0"
authors = ["Rasmus Karlsson <rasmus.karlsson@pajlada.com>"]

[dependencies]
serde = "1.0.70"
serde_derive = "1.0.70"
bincode = "1.0.1"

ctrlc = { version = "3.0", features = ["termination"] }
